export const desktopToolNames = [
  'list-instances',
  'check-for-user-changes',
  'get-workbook-xml',
  'apply-workbook',
  'list-worksheets',
  'list-dashboards',
  'get-worksheet-xml',
  'get-worksheet-summary-data',
  'apply-worksheet',
  'delete-worksheet',
  'refine-worksheet',
  'get-dashboard-xml',
  'apply-dashboard',
  'apply-dashboard-with-viewpoints',
  'build-and-apply-dashboard',
  'list-available-fields',
  'list-fields',
  'add-field',
  'remove-field',
  'resolve-field',
  'search-examples',
  'search-commands',
  'lookup-workbook-schema',
  'search-workbook-examples',
  'execute-tableau-command',
  'ask-user',
  'bind-template',
  'dashboard-auto-apply',
  'dashboard-health-check',
  'list-templates',
  'propose-template',
  'validate-proposal',
  'plan-dashboard-creation',
  'batch-create-and-cache-sheets',
  'build-and-apply-worksheet',
  'list-xml-templates',
  'validate-worksheet-xml',
  'validate-workbook-xml',
  'read-cached-xml',
  'write-cached-xml',
  'inject-template',
  'get-dashboard-guide',
  'list-knowledge-resources',
  'read-knowledge-resource',
] as const;
export type DesktopToolName = (typeof desktopToolNames)[number];

export function isDesktopToolName(value: unknown): value is DesktopToolName {
  return desktopToolNames.some((name) => name === value);
}
