import { makeApi, makeEndpoint, ZodiosEndpointDefinitions } from '@zodios/core';
import { z } from 'zod';

import { paginationParameters } from './paginationParameters.js';

const anyResponse = z.any();

const adminApi = makeApi([
  makeEndpoint({
    method: 'put',
    path: '/sites/:siteId/groupsets/:groupSetId/groups/:groupId',
    alias: 'addGroupToGroupSet',
    description: 'Adds group to a group set.',
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'post',
    path: '/sites/:siteId/groups/:groupId/users',
    alias: 'addUserToGroup',
    description: 'Adds one or more users to a group.',
    parameters: [{ name: 'Body', type: 'Body', schema: z.any() }],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'post',
    path: '/sites/:siteId/users',
    alias: 'addUserToSite',
    description: 'Adds a user to a site.',
    parameters: [{ name: 'Body', type: 'Body', schema: z.any() }],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'post',
    path: '/sites/:siteId/groups',
    alias: 'createGroup',
    description: 'Creates a group on a site.',
    parameters: [
      {
        name: 'asJob',
        type: 'Query',
        schema: z.boolean().optional(),
      },
      { name: 'Body', type: 'Body', schema: z.any() },
    ],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'post',
    path: '/sites/:siteId/groupsets',
    alias: 'createGroupSet',
    description: 'Creates a group set.',
    parameters: [{ name: 'Body', type: 'Body', schema: z.any() }],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'delete',
    path: '/sites/:siteId/groups/:groupId',
    alias: 'deleteGroup',
    description: 'Deletes a group.',
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'delete',
    path: '/sites/:siteId/groupsets/:groupSetId',
    alias: 'deleteGroupSet',
    description: 'Deletes a group set.',
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'post',
    path: '/sites/:siteId/users/delete',
    alias: 'deleteUsersFromSiteWithCsv',
    description: 'Deletes users from site via CSV multipart upload.',
    parameters: [{ name: 'Body', type: 'Body', schema: z.any() }],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'post',
    path: '/sites/:siteId/users/:userId/retrieveSavedCreds',
    alias: 'downloadUserCredentials',
    description: 'Downloads user credentials for migration.',
    parameters: [{ name: 'Body', type: 'Body', schema: z.any() }],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'get',
    path: '/sites/:siteId/users/:userId/groups',
    alias: 'getGroupsForUser',
    description: 'Gets groups for a user.',
    parameters: [...paginationParameters],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'get',
    path: '/sites/:siteId/groupsets/:groupSetId',
    alias: 'getGroupSet',
    description: 'Gets a group set.',
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'get',
    path: '/sites/:siteId/groups/:groupId/users',
    alias: 'getUsersInGroup',
    description: 'Gets users in a group.',
    parameters: [...paginationParameters],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'get',
    path: '/sites/:siteId/users',
    alias: 'getUsersOnSite',
    description: 'Gets users on a site.',
    parameters: [
      ...paginationParameters,
      { name: 'filter', type: 'Query', schema: z.string().optional() },
      { name: 'sort', type: 'Query', schema: z.string().optional() },
      { name: 'fields', type: 'Query', schema: z.string().optional() },
    ],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'post',
    path: '/sites/:siteId/users/import',
    alias: 'importUsersToSiteFromCsv',
    description: 'Imports users to site from CSV multipart upload.',
    parameters: [
      { name: 'isVerbose', type: 'Query', schema: z.boolean().optional() },
      { name: 'Body', type: 'Body', schema: z.any() },
    ],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'get',
    path: '/sites/:siteId/groupsets',
    alias: 'listGroupSets',
    description: 'Lists group sets.',
    parameters: [
      ...paginationParameters,
      { name: 'filter', type: 'Query', schema: z.string().optional() },
      { name: 'sort', type: 'Query', schema: z.string().optional() },
    ],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'get',
    path: '/sites/:siteId/groups',
    alias: 'queryGroups',
    description: 'Queries groups.',
    parameters: [
      ...paginationParameters,
      { name: 'filter', type: 'Query', schema: z.string().optional() },
      { name: 'sort', type: 'Query', schema: z.string().optional() },
    ],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'get',
    path: '/sites/:siteId/users/:userId',
    alias: 'queryUserOnSite',
    description: 'Queries a user on site.',
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'delete',
    path: '/sites/:siteId/groupsets/:groupSetId/groups/:groupId',
    alias: 'removeGroupFromGroupSet',
    description: 'Removes a group from group set.',
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'delete',
    path: '/sites/:siteId/users/:userId',
    alias: 'removeUserFromSite',
    description: 'Removes user from site.',
    parameters: [{ name: 'mapAssetsTo', type: 'Query', schema: z.string().optional() }],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'delete',
    path: '/sites/:siteId/groups/:groupId/users/:userId',
    alias: 'removeUserFromGroup',
    description: 'Removes one user from group.',
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'put',
    path: '/sites/:siteId/groups/:groupId/users/remove',
    alias: 'bulkRemoveUsersFromGroup',
    description: 'Bulk removes users from group.',
    parameters: [{ name: 'Body', type: 'Body', schema: z.any() }],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'put',
    path: '/sites/:siteId/groups/:groupId',
    alias: 'updateGroup',
    description: 'Updates a group.',
    parameters: [
      { name: 'asJob', type: 'Query', schema: z.boolean().optional() },
      { name: 'Body', type: 'Body', schema: z.any() },
    ],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'put',
    path: '/sites/:siteId/groupsets/:groupSetId',
    alias: 'updateGroupSet',
    description: 'Updates a group set.',
    parameters: [{ name: 'Body', type: 'Body', schema: z.any() }],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'put',
    path: '/sites/:siteId/users/:userId',
    alias: 'updateUser',
    description: 'Updates a user.',
    parameters: [{ name: 'Body', type: 'Body', schema: z.any() }],
    response: anyResponse,
  }),
  makeEndpoint({
    method: 'put',
    path: '/sites/:siteId/users/:userId/uploadSavedCreds',
    alias: 'uploadUserCredentials',
    description: 'Uploads user credentials to destination site.',
    parameters: [{ name: 'Body', type: 'Body', schema: z.any() }],
    response: anyResponse,
  }),
]);

export const adminApis = [...adminApi] as const satisfies ZodiosEndpointDefinitions;
