name: 'Run OAuth Tests'
description: 'Runs OAuth tests with required secrets'
runs:
  using: 'composite'
  steps:
    - name: OAuth Tests
      shell: bash
      run: npm run test:oauth
      env:
        SERVER: ${{ env.SERVER }}
        SITE_NAME: ${{ env.SITE_NAME }}
        OAUTH_ISSUER: http://127.0.0.1:3927
        OAUTH_JWE_PRIVATE_KEY: ${{ env.OAUTH_JWE_PRIVATE_KEY }}
        OAUTH_JWE_PRIVATE_KEY_PASSPHRASE: ${{ env.OAUTH_JWE_PRIVATE_KEY_PASSPHRASE }}
