import {
  buildTrexManifest,
  DATA_APP_MANIFEST_FILE,
  DataAppFramework,
  DataAppResource,
  DEFAULT_QUERY_ENDPOINT,
  extensionIdFor,
  firstDatasourceLuid,
  PLACEHOLDER_APP_URL,
  render,
  slugify,
} from './dataAppShared.js';

/**
 * File-content templates for a scaffolded Tableau data app.
 *
 * IMPORTANT: generated file contents intentionally avoid JS backticks and `${`
 * so they can live inside these TS template literals without escaping. Generated
 * apps therefore use string concatenation and (for the React variant) Preact's
 * `h()` instead of JSX/htm. The agent is free to switch to JSX afterward.
 */

const INDEX_HTML = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '  <meta charset="utf-8" />',
  '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
  '  <title>__APP_TITLE__</title>',
  '  <link rel="stylesheet" href="src/styles.css" />',
  '  <script src="https://tableau.github.io/extensions-api/lib/tableau.extensions.1.latest.min.js"></script>',
  '</head>',
  '<body>',
  '  <div id="app"><div class="loading">Loading…</div></div>',
  '  <script src="src/config.js"></script>',
  '  <script src="src/tableauData.js"></script>',
  '  __APP_SCRIPT_TAG__',
  '</body>',
  '</html>',
  '',
].join('\n');

const TABLEAU_DATA_SHIM_JS = [
  '// Data-access shim: the ONLY way this app gets data. It forwards requests to the',
  '// Tableau-hosted proxy and returns rows. Never hardcode data.',
  '//',
  '// The app can be wired to an arbitrary array of typed resources (datasource, view,',
  '// workbook, metric). Inspect window.tableauData.resources / .byName(name), then use',
  '// the matching method: query() for datasources, getViewData() for views,',
  '// getWorkbookViews() for workbooks, getMetrics() for Pulse metrics.',
  '(function () {',
  "  'use strict';",
  '  var params = new URLSearchParams(window.location.search);',
  '  var config = window.TABLEAU_APP_CONFIG || {};',
  '',
  '  var resources = config.resources || [];',
  "  var resourcesParam = params.get('resources');",
  '  if (resourcesParam) {',
  '    try { resources = JSON.parse(resourcesParam); } catch (e) { /* keep config resources */ }',
  '  }',
  '',
  "  var queryEndpoint = params.get('queryEndpoint') || config.queryEndpoint || '/query';",
  '',
  '  var resourcesByName = {};',
  '  resources.forEach(function (r) { if (r && r.name) resourcesByName[r.name] = r; });',
  '',
  '  function firstOfType(type) {',
  '    for (var i = 0; i < resources.length; i++) { if (resources[i].type === type) return resources[i]; }',
  '    return null;',
  '  }',
  '  var defaultDatasource = firstOfType("datasource");',
  "  var datasourceLuid = (defaultDatasource && defaultDatasource.luid) || config.datasourceLuid || '';",
  '',
  '  async function postJson(path, body) {',
  '    var res = await fetch(path, {',
  "      method: 'POST',",
  "      headers: { 'Content-Type': 'application/json' },",
  '      body: JSON.stringify(body)',
  '    });',
  '    var payload = await res.json().catch(function () { return {}; });',
  '    if (!res.ok) {',
  "      throw new Error((payload && payload.error) || ('Request failed with status ' + res.status));",
  '    }',
  '    return payload;',
  '  }',
  '',
  '  async function query(request) {',
  '    request = request || {};',
  '    var luid = request.datasourceLuid || datasourceLuid;',
  "    if (!luid) throw new Error('tableauData.query: no datasource configured. Pass datasourceLuid.');",
  '    if (!request.query || !Array.isArray(request.query.fields)) {',
  "      throw new Error('tableauData.query: request.query.fields (array) is required.');",
  '    }',
  '    var payload = await postJson(queryEndpoint, { datasourceLuid: luid, query: request.query, limit: request.limit });',
  '    return { columns: payload.columns || deriveColumns(payload.rows), rows: payload.rows || [] };',
  '  }',
  '',
  '  async function getViewData(request) {',
  '    request = request || {};',
  '    var view = firstOfType("view");',
  '    var luid = request.viewLuid || (view && view.luid);',
  "    if (!luid) throw new Error('tableauData.getViewData: no view configured. Pass viewLuid.');",
  "    var payload = await postJson('/view-data', { viewLuid: luid, maxRows: request.maxRows });",
  '    return { columns: payload.columns || deriveColumns(payload.rows), rows: payload.rows || [] };',
  '  }',
  '',
  '  async function getWorkbookViews(request) {',
  '    request = request || {};',
  '    var wb = firstOfType("workbook");',
  '    var luid = request.workbookLuid || (wb && wb.luid);',
  "    if (!luid) throw new Error('tableauData.getWorkbookViews: no workbook configured. Pass workbookLuid.');",
  "    return await postJson('/workbook-views', { workbookLuid: luid });",
  '  }',
  '',
  '  function metricIds(request) {',
  '    var ids = request.metricLuids;',
  '    if (!ids || !ids.length) {',
  '      ids = resources.filter(function (r) { return r.type === "metric"; }).map(function (r) { return r.luid; });',
  '    }',
  '    return ids;',
  '  }',
  '',
  '  // Metric metadata/specs only (cheap). For KPI numbers use getMetricValues.',
  '  async function getMetrics(request) {',
  '    request = request || {};',
  '    var ids = metricIds(request);',
  "    if (!ids.length) throw new Error('tableauData.getMetrics: no metric configured. Pass metricLuids.');",
  "    return await postJson('/pulse-metrics', { metricLuids: ids });",
  '  }',
  '',
  '  // Resolves current Pulse values: returns { metrics: [{ metric_id, name,',
  '  // value: { formatted_value, characterization } }] }. Requires Pulse insights enabled.',
  '  async function getMetricValues(request) {',
  '    request = request || {};',
  '    var ids = metricIds(request);',
  "    if (!ids.length) throw new Error('tableauData.getMetricValues: no metric configured. Pass metricLuids.');",
  "    return await postJson('/pulse-metric-values', { metricLuids: ids });",
  '  }',
  '',
  '  function deriveColumns(rows) {',
  '    if (!rows || !rows.length) return [];',
  '    return Object.keys(rows[0]);',
  '  }',
  '',
  '  window.tableauData = {',
  '    resources: resources,',
  '    resourcesByName: resourcesByName,',
  '    byName: function (name) { return resourcesByName[name]; },',
  '    query: query,',
  '    getViewData: getViewData,',
  '    getWorkbookViews: getWorkbookViews,',
  '    getMetrics: getMetrics,',
  '    getMetricValues: getMetricValues,',
  '    datasourceLuid: datasourceLuid,',
  '    queryEndpoint: queryEndpoint',
  '  };',
  '})();',
  '',
].join('\n');

const APP_JS_HTML = [
  "'use strict';",
  '(function () {',
  "  var root = document.getElementById('app');",
  '',
  '  async function main() {',
  '    try {',
  '      if (window.tableau && window.tableau.extensions) {',
  '        await window.tableau.extensions.initializeAsync();',
  '      }',
  '    } catch (e) {',
  '      // Running outside Tableau (local preview): continue without workbook context.',
  "      console.warn('Extensions API not initialized:', e);",
  '    }',
  '    render();',
  '  }',
  '',
  '  function render() {',
  "    var luid = (window.tableauData && window.tableauData.datasourceLuid) || 'not configured';",
  "    root.innerHTML = '';",
  "    var shell = document.createElement('div');",
  "    shell.className = 'app-shell';",
  '    shell.innerHTML =',
  "      '<h1>' + escapeHtml(document.title) + '</h1>' +",
  '      \'<p class="takeaway">This data app is scaffolded and ready. Edit <code>src/app.js</code> to build your visualization.</p>\' +',
  "      '<p class=\"hint\">Data source: <code>' + escapeHtml(luid) + '</code></p>' +",
  '      \'<p class="hint">Fetch live data with <code>window.tableauData.query(...)</code>. Never hardcode data.</p>\';',
  '    root.appendChild(shell);',
  '',
  '    // EXAMPLE (replace the field captions with real fields from your data',
  '    // source — discover them with the get-datasource-metadata MCP tool):',
  '    //',
  '    // var result = await window.tableauData.query({',
  '    //   query: { fields: [',
  "    //     { fieldCaption: 'Category' },",
  "    //     { fieldCaption: 'Sales', function: 'SUM', sortDirection: 'DESC' }",
  '    //   ] },',
  '    //   limit: 100',
  '    // });',
  '    // renderTable(result);',
  '  }',
  '',
  '  function renderTable(result) {',
  "    var table = document.createElement('table');",
  "    table.className = 'data-table';",
  "    var thead = document.createElement('thead');",
  "    var trh = document.createElement('tr');",
  '    (result.columns || []).forEach(function (c) {',
  "      var th = document.createElement('th');",
  '      th.textContent = c;',
  '      trh.appendChild(th);',
  '    });',
  '    thead.appendChild(trh);',
  '    table.appendChild(thead);',
  "    var tbody = document.createElement('tbody');",
  '    (result.rows || []).forEach(function (row) {',
  "      var tr = document.createElement('tr');",
  '      (result.columns || []).forEach(function (c) {',
  "        var td = document.createElement('td');",
  "        td.textContent = String(row[c] == null ? '' : row[c]);",
  '        tr.appendChild(td);',
  '      });',
  '      tbody.appendChild(tr);',
  '    });',
  '    table.appendChild(tbody);',
  '    root.appendChild(table);',
  '  }',
  '',
  '  function escapeHtml(s) {',
  '    return String(s).replace(/[&<>"\']/g, function (c) {',
  '      return ({',
  "        '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', \"'\": '&apos;'",
  '      })[c];',
  '    });',
  '  }',
  '',
  '  // Exposed for convenience while iterating.',
  '  window.__app = { renderTable: renderTable };',
  '  main();',
  '})();',
  '',
].join('\n');

const APP_JS_REACT = [
  "import { h, render } from 'https://esm.sh/preact@10.22.0';",
  "import { useEffect, useState } from 'https://esm.sh/preact@10.22.0/hooks';",
  '',
  '// Build-free Preact via ESM CDN using h() (no JSX/build step). Switch to JSX',
  '// or htm afterward if you prefer. Never hardcode data: use window.tableauData.query.',
  'function App() {',
  '  var state = useState(false);',
  '  var ready = state[0];',
  '  var setReady = state[1];',
  '',
  '  useEffect(function () {',
  '    (async function () {',
  '      try {',
  '        if (window.tableau && window.tableau.extensions) {',
  '          await window.tableau.extensions.initializeAsync();',
  '        }',
  '      } catch (e) {',
  "        console.warn('Extensions API not initialized:', e);",
  '      }',
  '      setReady(true);',
  '    })();',
  '  }, []);',
  '',
  "  if (!ready) return h('div', { class: 'loading' }, 'Loading…');",
  '',
  "  var luid = (window.tableauData && window.tableauData.datasourceLuid) || 'not configured';",
  "  return h('div', { class: 'app-shell' }, [",
  "    h('h1', null, document.title),",
  "    h('p', { class: 'takeaway' }, 'This data app is scaffolded and ready. Edit src/app.js to build your visualization.'),",
  "    h('p', { class: 'hint' }, ['Data source: ', h('code', null, luid)]),",
  "    h('p', { class: 'hint' }, 'Fetch live data with window.tableauData.query(...). Never hardcode data.')",
  '  ]);',
  '}',
  '',
  '// EXAMPLE query (replace field captions with real fields from your data source;',
  '// discover them with the get-datasource-metadata MCP tool):',
  '//',
  '// var result = await window.tableauData.query({',
  "//   query: { fields: [{ fieldCaption: 'Category' }, { fieldCaption: 'Sales', function: 'SUM' }] },",
  '//   limit: 100',
  '// });',
  '',
  "render(h(App), document.getElementById('app'));",
  '',
].join('\n');

const STYLES_CSS = [
  ':root { --fg: #1a1a2e; --muted: #6b7280; --accent: #2563eb; --bg: #ffffff; }',
  '* { box-sizing: border-box; }',
  'body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: var(--fg); background: var(--bg); }',
  '#app { padding: 16px; }',
  '.loading { color: var(--muted); padding: 24px; }',
  '.error { color: #b91c1c; padding: 16px; border: 1px solid #fecaca; border-radius: 8px; background: #fef2f2; }',
  '.app-shell h1 { font-size: 18px; margin: 0 0 8px; }',
  '.takeaway { font-size: 14px; margin: 0 0 12px; }',
  '.hint { font-size: 12px; color: var(--muted); margin: 4px 0; }',
  'code { background: #f3f4f6; padding: 1px 4px; border-radius: 4px; font-size: 0.92em; }',
  '.data-table { border-collapse: collapse; width: 100%; font-size: 13px; margin-top: 12px; }',
  '.data-table th, .data-table td { text-align: left; padding: 6px 10px; border-bottom: 1px solid #e5e7eb; }',
  '.data-table th { color: var(--muted); font-weight: 600; }',
  '',
].join('\n');

const SERVER_JS = [
  "'use strict';",
  '// Tableau data app host + data proxy.',
  '// Serves the static app bundle AND proxies Tableau data requests (VDS, view data,',
  '// workbook views, Pulse) using a single service PAT (no per-user context here).',
  "const path = require('path');",
  "const express = require('express');",
  "const cors = require('cors');",
  '',
  'const app = express();',
  'app.use(cors());',
  "app.use(express.json({ limit: '4mb' }));",
  '',
  "const SERVER = (process.env.TABLEAU_SERVER || '').replace(/\\/+$/, '');",
  "const SITE_CONTENT_URL = process.env.TABLEAU_SITE_NAME || process.env.SITE_NAME || '';",
  "const PAT_NAME = process.env.PAT_NAME || '';",
  "const PAT_VALUE = process.env.PAT_VALUE || '';",
  "const API_VERSION = process.env.TABLEAU_API_VERSION || '3.21';",
  '',
  '// --- Cached Tableau session ----------------------------------------------',
  '// A PAT can only hold one active session per token name: signing in again',
  '// invalidates the previous session. A page that fires several queries in',
  '// parallel would therefore race-invalidate itself (and hit 429s) if each',
  '// request signed in. So we keep ONE in-memory session, reuse it (single-flight',
  '// on cache miss), refresh it before the ~240-min idle limit, and re-auth on 401.',
  'const SESSION_TTL_MS = 9 * 60 * 1000;',
  'let cachedSession = null;',
  'let signInFlight = null;',
  '',
  'async function signInRaw() {',
  '  if (!SERVER || !PAT_NAME || !PAT_VALUE) {',
  "    throw new Error('Proxy missing Tableau credentials: set TABLEAU_SERVER, PAT_NAME, PAT_VALUE.');",
  '  }',
  "  const res = await fetch(SERVER + '/api/' + API_VERSION + '/auth/signin', {",
  "    method: 'POST',",
  "    headers: { 'Content-Type': 'application/json', 'Accept': 'application/json' },",
  '    body: JSON.stringify({',
  '      credentials: {',
  '        personalAccessTokenName: PAT_NAME,',
  '        personalAccessTokenSecret: PAT_VALUE,',
  '        site: { contentUrl: SITE_CONTENT_URL }',
  '      }',
  '    })',
  '  });',
  '  const data = await res.json().catch(function () { return {}; });',
  '  if (!res.ok) {',
  "    throw new Error('Tableau sign-in failed (' + res.status + '): ' + JSON.stringify(data));",
  '  }',
  '  return { token: data.credentials.token, siteId: data.credentials.site.id, expiresAt: Date.now() + SESSION_TTL_MS };',
  '}',
  '',
  'async function getSession() {',
  '  if (cachedSession && cachedSession.expiresAt > Date.now()) {',
  '    return cachedSession;',
  '  }',
  '  if (!signInFlight) {',
  '    signInFlight = signInRaw()',
  '      .then(function (s) { cachedSession = s; return s; })',
  '      .finally(function () { signInFlight = null; });',
  '  }',
  '  return await signInFlight;',
  '}',
  '',
  'function invalidateSession() { cachedSession = null; }',
  '',
  '// Runs an authenticated request; on 401 it refreshes the session once and retries.',
  '// makeRequest receives the session and returns a fetch() promise.',
  'async function tableauRequest(makeRequest) {',
  '  let s = await getSession();',
  '  let res = await makeRequest(s);',
  '  if (res.status === 401) {',
  '    invalidateSession();',
  '    s = await getSession();',
  '    res = await makeRequest(s);',
  '  }',
  '  return res;',
  '}',
  '',
  'function pulseHeaders(s) {',
  "  return { 'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Tableau-Auth': s.token };",
  '}',
  '',
  '// --- Endpoints -----------------------------------------------------------',
  "app.post('/query', async function (req, res) {",
  '  const body = req.body || {};',
  '  if (!body.datasourceLuid || !body.query) {',
  "    res.status(400).json({ error: 'datasourceLuid and query are required.' });",
  '    return;',
  '  }',
  '  try {',
  "    const options = { returnFormat: 'OBJECTS', disaggregate: false };",
  '    if (body.limit) options.rowLimit = body.limit;',
  '    const vdsRes = await tableauRequest(function (s) {',
  "      return fetch(SERVER + '/api/v1/vizql-data-service/query-datasource', {",
  "        method: 'POST',",
  "        headers: { 'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Tableau-Auth': s.token },",
  '        body: JSON.stringify({ datasource: { datasourceLuid: body.datasourceLuid }, query: body.query, options: options })',
  '      });',
  '    });',
  '    const payload = await vdsRes.json().catch(function () { return {}; });',
  '    if (!vdsRes.ok) {',
  "      const message = (payload && payload.message) || 'VizQL Data Service query failed.';",
  '      const out = { error: message, detail: payload };',
  '      const hint = vdsHint(message);',
  '      if (hint) { out.actionable = hint; }',
  '      res.status(vdsRes.status).json(out);',
  '      return;',
  '    }',
  '    const rows = payload.data || [];',
  '    res.json({ columns: rows.length ? Object.keys(rows[0]) : [], rows: rows });',
  '  } catch (err) {',
  '    res.status(500).json({ error: err && err.message ? err.message : String(err) });',
  '  }',
  '});',
  '',
  '// View data (REST): returns the summary data of a published view as rows.',
  "app.post('/view-data', async function (req, res) {",
  '  const body = req.body || {};',
  '  if (!body.viewLuid) {',
  "    res.status(400).json({ error: 'viewLuid is required.' });",
  '    return;',
  '  }',
  '  try {',
  '    const r = await tableauRequest(function (s) {',
  "      let url = SERVER + '/api/' + API_VERSION + '/sites/' + s.siteId + '/views/' + body.viewLuid + '/data';",
  "      if (body.maxRows) url += '?maxRows=' + encodeURIComponent(body.maxRows);",
  "      return fetch(url, { headers: { 'X-Tableau-Auth': s.token, 'Accept': 'text/csv' } });",
  '    });',
  '    const text = await r.text();',
  '    if (!r.ok) {',
  "      res.status(r.status).json({ error: 'View data request failed.', detail: text });",
  '      return;',
  '    }',
  '    const parsed = parseCsv(text);',
  '    res.json({ columns: parsed.columns, rows: parsed.rows });',
  '  } catch (err) {',
  '    res.status(500).json({ error: err && err.message ? err.message : String(err) });',
  '  }',
  '});',
  '',
  '// Workbook (REST): returns the views belonging to a workbook so the app can drill',
  '// into per-view data via /view-data.',
  "app.post('/workbook-views', async function (req, res) {",
  '  const body = req.body || {};',
  '  if (!body.workbookLuid) {',
  "    res.status(400).json({ error: 'workbookLuid is required.' });",
  '    return;',
  '  }',
  '  try {',
  '    const r = await tableauRequest(function (s) {',
  "      const url = SERVER + '/api/' + API_VERSION + '/sites/' + s.siteId + '/workbooks/' + body.workbookLuid + '/views';",
  "      return fetch(url, { headers: { 'X-Tableau-Auth': s.token, 'Accept': 'application/json' } });",
  '    });',
  '    const payload = await r.json().catch(function () { return {}; });',
  '    if (!r.ok) {',
  "      res.status(r.status).json({ error: 'Workbook views request failed.', detail: payload });",
  '      return;',
  '    }',
  '    const list = (payload.views && payload.views.view) || [];',
  '    const views = list.map(function (v) { return { id: v.id, name: v.name, contentUrl: v.contentUrl }; });',
  '    res.json({ views: views });',
  '  } catch (err) {',
  '    res.status(500).json({ error: err && err.message ? err.message : String(err) });',
  '  }',
  '});',
  '',
  '// Pulse metrics (REST): batch-gets metric definitions/specs by metric LUID.',
  '// This is metadata only (no current value); use /pulse-metric-values for KPI numbers.',
  "app.post('/pulse-metrics', async function (req, res) {",
  '  const body = req.body || {};',
  '  if (!body.metricLuids || !body.metricLuids.length) {',
  "    res.status(400).json({ error: 'metricLuids (array) is required.' });",
  '    return;',
  '  }',
  '  try {',
  '    const r = await tableauRequest(function (s) {',
  "      return fetch(SERVER + '/api/-/pulse/metrics:batchGet', { method: 'POST', headers: pulseHeaders(s), body: JSON.stringify({ metric_ids: body.metricLuids }) });",
  '    });',
  '    const payload = await r.json().catch(function () { return {}; });',
  '    if (!r.ok) {',
  "      res.status(r.status).json({ error: 'Pulse metrics request failed.', detail: payload });",
  '      return;',
  '    }',
  '    res.json({ metrics: payload.metrics || [] });',
  '  } catch (err) {',
  '    res.status(500).json({ error: err && err.message ? err.message : String(err) });',
  '  }',
  '});',
  '',
  '// Pulse metric VALUES: resolves the current aggregate value (+ characterization)',
  '// per metric by chaining metrics:batchGet -> definitions:batchGet -> insights/ban.',
  '// Requires Pulse insights enabled on the site. Value extraction is best-effort;',
  '// the raw bundle is returned too so the app can read other facts if needed.',
  "app.post('/pulse-metric-values', async function (req, res) {",
  '  const body = req.body || {};',
  '  const ids = body.metricLuids;',
  '  if (!ids || !ids.length) {',
  "    res.status(400).json({ error: 'metricLuids (array) is required.' });",
  '    return;',
  '  }',
  '  try {',
  '    const metricsRes = await tableauRequest(function (s) {',
  "      return fetch(SERVER + '/api/-/pulse/metrics:batchGet', { method: 'POST', headers: pulseHeaders(s), body: JSON.stringify({ metric_ids: ids }) });",
  '    });',
  '    const metricsPayload = await metricsRes.json().catch(function () { return {}; });',
  '    if (!metricsRes.ok) {',
  "      res.status(metricsRes.status).json({ error: 'Pulse metrics lookup failed.', detail: metricsPayload });",
  '      return;',
  '    }',
  '    const metrics = metricsPayload.metrics || [];',
  '    const defIds = metrics.map(function (m) { return m.definition_id; }).filter(Boolean);',
  '    const definitionsById = {};',
  '    if (defIds.length) {',
  '      const defRes = await tableauRequest(function (s) {',
  "        return fetch(SERVER + '/api/-/pulse/definitions:batchGet', { method: 'POST', headers: pulseHeaders(s), body: JSON.stringify({ definition_ids: defIds }) });",
  '      });',
  '      const defPayload = await defRes.json().catch(function () { return {}; });',
  '      (defPayload.definitions || []).forEach(function (d) {',
  '        const id = d.metadata && d.metadata.id;',
  '        if (id) { definitionsById[id] = d; }',
  '      });',
  '    }',
  '    const results = [];',
  '    for (const metric of metrics) {',
  '      const def = definitionsById[metric.definition_id];',
  '      let value = null;',
  '      try {',
  '        if (def && def.specification) {',
  '          const bundleReq = buildPulseBundleRequest(metric, def);',
  '          const bundleRes = await tableauRequest(function (s) {',
  "            return fetch(SERVER + '/api/-/pulse/insights/ban', { method: 'POST', headers: pulseHeaders(s), body: JSON.stringify(bundleReq) });",
  '          });',
  '          const bundlePayload = await bundleRes.json().catch(function () { return {}; });',
  '          if (bundleRes.ok) { value = extractPulseValue(bundlePayload); }',
  '        }',
  '      } catch (e) { /* best effort per metric */ }',
  '      results.push({',
  '        metric_id: metric.id,',
  '        definition_id: metric.definition_id,',
  '        name: (def && def.metadata && def.metadata.name) || null,',
  '        value: value',
  '      });',
  '    }',
  '    res.json({ metrics: results });',
  '  } catch (err) {',
  '    res.status(500).json({ error: err && err.message ? err.message : String(err) });',
  '  }',
  '});',
  '',
  'function buildPulseBundleRequest(metric, def) {',
  '  const spec = def.specification || {};',
  '  return {',
  '    bundle_request: {',
  '      version: 1,',
  '      options: {',
  "        output_format: 'OUTPUT_FORMAT_TEXT',",
  "        time_zone: 'UTC',",
  "        language: 'LANGUAGE_EN_US',",
  "        locale: 'LOCALE_EN_US'",
  '      },',
  '      input: {',
  '        metadata: {',
  '          name: (def.metadata && def.metadata.name) || undefined,',
  '          metric_id: metric.id,',
  '          definition_id: metric.definition_id',
  '        },',
  '        metric: {',
  '          definition: {',
  '            datasource: { id: (spec.datasource && spec.datasource.id) || metric.datasource_luid },',
  '            basic_specification: spec.basic_specification || {},',
  '            is_running_total: !!spec.is_running_total',
  '          },',
  '          metric_specification: metric.specification || {},',
  '          extension_options: def.extension_options || {},',
  '          representation_options: def.representation_options || {},',
  '          insights_options: def.insights_options || {}',
  '        }',
  '      }',
  '    }',
  '  };',
  '}',
  '',
  '// Walks the insight bundle for the first formatted value + characterization.',
  'function extractPulseValue(bundle) {',
  '  let formatted = null;',
  '  (function walk(node) {',
  "    if (formatted || !node || typeof node !== 'object') return;",
  "    if (node.value && typeof node.value.formatted_value === 'string') { formatted = node.value.formatted_value; return; }",
  '    for (const k in node) {',
  '      if (Object.prototype.hasOwnProperty.call(node, k)) { walk(node[k]); }',
  '    }',
  '  })(bundle);',
  '  let characterization = null;',
  '  try { characterization = bundle.bundle_response.result.characterization || null; } catch (e) { /* ignore */ }',
  '  if (!formatted && !characterization) return null;',
  '  return { formatted_value: formatted, characterization: characterization };',
  '}',
  '',
  '// Turns known VDS error shapes into an actionable hint for the app/agent.',
  'function vdsHint(message) {',
  "  const m = String(message || '');",
  '  if (/Unknown Field/i.test(m)) {',
  "    return 'This caption is in datasource metadata but is not callable via VDS (often a calc or joined column). Verify it with a single-field query, or choose a different caption.';",
  '  }',
  '  if (/does not exist in your database/i.test(m)) {',
  "    return 'The field exists in metadata but the underlying column is unavailable for this field/filter/group combination. Try removing it from one role (e.g. drop the date filter, or do not both group and MATCH-filter the same field), or query it separately.';",
  '  }',
  '  return undefined;',
  '}',
  '',
  'function parseCsv(text) {',
  '  const lines = String(text).split(/\\r\\n|\\n/).filter(function (l) { return l.length > 0; });',
  '  if (!lines.length) return { columns: [], rows: [] };',
  '  const columns = splitCsvLine(lines[0]);',
  '  const rows = [];',
  '  for (let i = 1; i < lines.length; i++) {',
  '    const vals = splitCsvLine(lines[i]);',
  '    const row = {};',
  "    for (let j = 0; j < columns.length; j++) { row[columns[j]] = vals[j] != null ? vals[j] : ''; }",
  '    rows.push(row);',
  '  }',
  '  return { columns: columns, rows: rows };',
  '}',
  '',
  'function splitCsvLine(line) {',
  '  const out = [];',
  "  let cur = '';",
  '  let inQ = false;',
  '  for (let i = 0; i < line.length; i++) {',
  '    const c = line[i];',
  '    if (inQ) {',
  "      if (c === '\"') {",
  "        if (line[i + 1] === '\"') { cur += '\"'; i++; } else { inQ = false; }",
  '      } else { cur += c; }',
  '    } else {',
  "      if (c === '\"') { inQ = true; }",
  "      else if (c === ',') { out.push(cur); cur = ''; }",
  '      else { cur += c; }',
  '    }',
  '  }',
  '  out.push(cur);',
  '  return out;',
  '}',
  '',
  "app.get('/healthz', function (req, res) { res.json({ ok: true }); });",
  'app.use(express.static(path.join(__dirname)));',
  '',
  'const port = process.env.PORT || 3000;',
  'app.listen(port, function () {',
  "  console.log('Tableau data app + data proxy listening on port ' + port);",
  '});',
  '',
].join('\n');

const PACKAGE_JSON = [
  '{',
  '  "name": "__APP_SLUG__",',
  '  "version": "1.0.0",',
  '  "private": true,',
  '  "description": "Tableau-hosted vibe-coded data app + VizQL Data Service proxy",',
  '  "scripts": {',
  '    "start": "node server.js"',
  '  },',
  '  "engines": {',
  '    "node": ">=18"',
  '  },',
  '  "dependencies": {',
  '    "cors": "^2.8.5",',
  '    "express": "^4.19.2"',
  '  }',
  '}',
  '',
].join('\n');

const PROCFILE = 'web: node server.js\n';

const GITIGNORE = ['node_modules/', '.DS_Store', '*.log', ''].join('\n');

const README_MD = [
  '# __APP_TITLE__',
  '',
  'A vibe-coded Tableau data app, packaged as a Dashboard Extension and hosted by',
  'Tableau (faked via Heroku in this prototype).',
  '',
  '## How it works',
  '',
  '- The app is a static bundle (index.html + src/) loaded inside a Tableau dashboard',
  '  as a Dashboard Extension (see manifest.trex).',
  '- It NEVER hardcodes data. All data comes through the window.tableauData shim, which',
  '  posts to the co-hosted proxy (server.js) and returns rows.',
  '- The proxy authenticates to Tableau with a service PAT.',
  '',
  '## Configured resources',
  '',
  'This app is wired to one or more typed Tableau resources (see dataapp.json and',
  'src/config.js). Inspect them at runtime via window.tableauData.resources and',
  'window.tableauData.byName(name). Each has a type: datasource | view | workbook | metric.',
  '',
  'Data-access methods (all return { columns, rows } unless noted):',
  '- Datasource: window.tableauData.query({ datasourceLuid?, query: { fields: [...] }, limit? })',
  '- View:       window.tableauData.getViewData({ viewLuid?, maxRows? })',
  '- Workbook:   window.tableauData.getWorkbookViews({ workbookLuid? }) -> { views: [...] }',
  '- Metric:     window.tableauData.getMetrics({ metricLuids? }) -> { metrics: [...] } (specs only)',
  '- Metric KPI: window.tableauData.getMetricValues({ metricLuids? }) -> { metrics: [{ value: { formatted_value } }] }',
  '',
  'When a LUID is omitted, all configured resources of that type are used (metrics) or the first (others).',
  '',
  '## Develop',
  '',
  '1. Edit src/app.js to build your visualization.',
  '2. Discover real field captions with the get-datasource-metadata MCP tool.',
  '3. Query live data via the methods above. Never hardcode data.',
  '',
  '## Run locally',
  '',
  '    npm install',
  '    TABLEAU_SERVER=https://your-server PAT_NAME=name PAT_VALUE=secret \\',
  '      TABLEAU_SITE_NAME=your-site npm start',
  '',
  'Then open http://localhost:3000/ (resources are read from src/config.js).',
  '',
  '## Deploy / load',
  '',
  'Use the deploy-data-app MCP tool to host this and produce the final .trex (saved',
  'to your Downloads). In Tableau Desktop, add an Extension object to a dashboard and',
  'select the downloaded .trex.',
  '',
].join('\n');

const AGENTS_MD = [
  '# Agent contract — __APP_TITLE__',
  '',
  'This is a Tableau data app scaffolded by the tableau-mcp data-app tools. If you are',
  'an AI agent editing this project, follow these rules so the app actually works',
  'as a live Tableau data app.',
  '',
  '## The cardinal rule: never hardcode data',
  '',
  'All data MUST be fetched at runtime through the `window.tableauData` shim',
  '(src/tableauData.js), which proxies to live Tableau data. Do NOT paste rows,',
  'records, or arrays of data values into the app. The whole point is live data.',
  '',
  '## Do not rewrite generated plumbing',
  '',
  'These files are managed by the toolchain. Do not rewrite them (write-data-app-file',
  'blocks them unless you pass allowProtected: true, which you should rarely need):',
  '- `src/tableauData.js` — the data-access shim (a fixed contract)',
  '- `server.js` — the co-hosted proxy + cached Tableau session',
  '- `dataapp.json` — the canonical resource manifest',
  '- `src/config.js` — generated from dataapp.json',
  '',
  '## Where you write code',
  '',
  'Build your app in `src/app.js` (and add files under `src/` as needed). After',
  '`tableau.extensions.initializeAsync()`, fetch data via the shim:',
  '- Datasource: `window.tableauData.query({ datasourceLuid?, query: { fields: [...] }, limit? })`',
  '- View:       `window.tableauData.getViewData({ viewLuid?, maxRows? })`',
  '- Workbook:   `window.tableauData.getWorkbookViews({ workbookLuid? })`',
  '- Metric:     `window.tableauData.getMetrics({ metricLuids? })` (specs)',
  '- Metric KPI: `window.tableauData.getMetricValues({ metricLuids? })` (current value)',
  '',
  'Configured resources are available at `window.tableauData.resources` and',
  '`window.tableauData.byName(name)`.',
  '',
  '## Workflow',
  '',
  '1. Discover real field captions with the `get-datasource-metadata` MCP tool — never',
  '   guess field names. Metadata can list more fields than VDS accepts; if a caption',
  '   errors as "Unknown Field", confirm it with a tiny one-field `query-datasource`.',
  '2. Place code with `write-data-app-file`; inspect with `read-data-app-file` /',
  '   `list-data-app-files` (essential if you have no direct filesystem access).',
  '3. Run `package-data-app` to validate the project structure and regenerate manifest.trex.',
  '4. Run `deploy-data-app` to host the app and produce the final .trex. It health-checks',
  '   the live app and returns the shipped file manifest — verify those before declaring success.',
  '',
].join('\n');

/**
 * Builds `src/config.js`, which inlines the resource list for the browser. The
 * deploy step also encodes resources as URL query params on the .trex source URL;
 * URL params take precedence over this file.
 */
function buildConfigJs(resources: DataAppResource[]): string {
  const config = {
    queryEndpoint: DEFAULT_QUERY_ENDPOINT,
    datasourceLuid: firstDatasourceLuid(resources),
    resources,
  };
  return [
    '// GENERATED FROM dataapp.json — do not edit by hand. dataapp.json is the canonical',
    '// resource source; this file inlines it so the browser can read it synchronously.',
    'window.TABLEAU_APP_CONFIG = ' + JSON.stringify(config, null, 2) + ';',
    '',
  ].join('\n');
}

/** Machine-readable manifest the package/deploy tools read (no JS parsing needed). */
function buildDataAppManifest({
  appName,
  appTitle,
  resources,
  framework,
}: {
  appName: string;
  appTitle: string;
  resources: DataAppResource[];
  framework: DataAppFramework;
}): string {
  return (
    JSON.stringify(
      {
        appName,
        appTitle,
        framework,
        queryEndpoint: DEFAULT_QUERY_ENDPOINT,
        resources,
      },
      null,
      2,
    ) + '\n'
  );
}

export function getScaffoldFiles({
  appName,
  appTitle,
  resources,
  framework,
}: {
  appName: string;
  appTitle: string;
  resources: DataAppResource[];
  framework: DataAppFramework;
}): Record<string, string> {
  const appScriptTag =
    framework === 'react'
      ? '<script type="module" src="src/app.js"></script>'
      : '<script src="src/app.js"></script>';

  const vars = {
    APP_TITLE: appTitle,
    APP_SLUG: slugify(appName),
    APP_SCRIPT_TAG: appScriptTag,
  };

  return {
    'index.html': render(INDEX_HTML, vars),
    'src/config.js': buildConfigJs(resources),
    'src/tableauData.js': TABLEAU_DATA_SHIM_JS,
    'src/app.js': framework === 'react' ? APP_JS_REACT : APP_JS_HTML,
    'src/styles.css': STYLES_CSS,
    'server.js': SERVER_JS,
    'package.json': render(PACKAGE_JSON, vars),
    Procfile: PROCFILE,
    '.gitignore': GITIGNORE,
    'README.md': render(README_MD, vars),
    'AGENTS.md': render(AGENTS_MD, vars),
    [DATA_APP_MANIFEST_FILE]: buildDataAppManifest({ appName, appTitle, resources, framework }),
    'manifest.trex': buildTrexManifest({
      appName: appTitle,
      extensionId: extensionIdFor(appName),
      appUrl: PLACEHOLDER_APP_URL,
    }),
  };
}
