name: 'Run OAuth Tableau Authorization Tests'
description: 'Runs OAuth tests with Tableau authorization with required secrets'
runs:
  using: 'composite'
  steps:
    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps
    - name: OAuth Tableau Authorization Tests
      shell: bash
      run: npm run test:oauth:tableau
      env:
        OAUTH_ISSUER: https://sso.online.dev.tabint.net
