name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['>=22.7.5 <23', '24.x']
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: npm ci

      - name: TypeScript compilation
        run: npx tsc

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Build Docker image
        run: npm run build:docker

      - name: Build NPM package
        run: npm pack

      - name: Tests
        run: npm run coverage

      - name: E2E Tests
        run: npm run test:e2e
        env:
          SERVER: ${{ secrets.E2E_TEST_SERVER }}
          SITE_NAME: ${{ secrets.E2E_TEST_SITE_NAME }}
          AUTH: ${{ secrets.E2E_TEST_AUTH }}
          JWT_SUB_CLAIM: ${{ secrets.E2E_TEST_JWT_SUB_CLAIM }}
          CONNECTED_APP_CLIENT_ID: ${{ secrets.E2E_TEST_CONNECTED_APP_CLIENT_ID }}
          CONNECTED_APP_SECRET_ID: ${{ secrets.E2E_TEST_CONNECTED_APP_SECRET_ID }}
          CONNECTED_APP_SECRET_VALUE: ${{ secrets.E2E_TEST_CONNECTED_APP_SECRET_VALUE }}

      - name: Build Claude MCP Bundle
        run: |
          npm run build:manifest:script
          npm run build:manifest
          npm ci --omit=dev
          npx -y @anthropic-ai/mcpb pack . tableau-mcp.mcpb

      - name: Report code coverage
        if: matrix.node-version == '>=22.7.5 <23'
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/cobertura-coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-node${{ matrix.node-version == '>=22.7.5 <23' && '22.x' || matrix.node-version }}
          if-no-files-found: error
          path: |
            build/
            junit/
            tableau-mcp.mcpb
