name: Publish
on:
  push:
    branches:
      - 'anyoung/npmjs'
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Needed for npm provenance
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: |
          git fetch --tags
          git checkout v1.8.0
          npm ci
          npm run build
          npm publish --provenance --dry-run
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
