name: Publish
on:
  release:
    types: [published]
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Needed for OIDC authentication
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: |
          git fetch --tags
          git checkout -b publish ${{ github.event.release.tag_name }}
          npm install -g npm@latest
          npm ci
          npm run build
          npm publish
  upload-mcpb:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to upload release assets
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: |
          git fetch --tags
          git checkout -b mcpb ${{ github.event.release.tag_name }}
          npm ci
          npm run build
          npm run build:manifest:script
          npm run build:manifest
          npm ci --omit=dev
          npx -y @anthropic-ai/mcpb pack . tableau-mcp-${{ github.event.release.tag_name }}.mcpb
      - name: Upload mcpb to release
        run: |
          gh release upload ${{github.event.release.tag_name}} tableau-mcp-${{ github.event.release.tag_name }}.mcpb
        env:
          GITHUB_TOKEN: ${{ github.token }}
