name: 'Tag for Release'
on:
  push:
    branches:
      - main
      - anyoung/versions

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tag
        id: tag
        run: |
          git fetch --tags
          git rev-list --tags --max-count=1
          git describe --tags
          latest=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "")
          echo "Current latest tag: $latest"
          echo "LATEST=$latest" >> $GITHUB_ENV
          version=$(grep -oP '"version": "\K[^"]+' package.json)
          echo "package.json version: $version"
          echo "TAG=v$version" >> $GITHUB_ENV

      - name: Push tag
        run: |
          if [ "$TAG" != "$LATEST" ]; then
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git tag $TAG
            git push origin $TAG
          else
            echo "Tag $TAG already exists, skipping"
          fi
