name: 'tag'
on:
  push:
    branches:
      - main
      - anyoung/versions
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tag
        id: tag
        run: |
          version=$(grep -oP '"version": "\K[^"]+' package.json)
          echo "TAG=v$version" >> $GITHUB_ENV

      - name: Push tag
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}
